# Generated by Django 4.1.5 on 2023-01-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.barcodes')),
            ],
        ),
        migrations.CreateModel(
            name='TechInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stock', models.IntegerField()),
                ('num_available', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.techcategories')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.itemnames')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.manufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='InOutStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in', models.BooleanField(default=True)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.barcodes')),
            ],
        ),
        migrations.AddField(
            model_name='barcodes',
            name='tech_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.techinventory'),
        ),
    ]
