# Generated by Django 4.1.5 on 2023-01-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnames',
            options={'verbose_name_plural': 'Item Names'},
        ),
    ]
