# Generated by Django 4.1.5 on 2023-01-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManager', '0002_alter_itemnames_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcodes',
            options={'verbose_name_plural': 'Barcodes'},
        ),
        migrations.AlterModelOptions(
            name='manufacturers',
            options={'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='techcategories',
            options={'verbose_name_plural': 'Tech Categories'},
        ),
    ]
