# Generated by Django 4.1.5 on 2023-01-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManager', '0003_alter_barcodes_options_alter_manufacturers_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InOutStatus',
            new_name='ItemStatus',
        ),
        migrations.AlterModelOptions(
            name='itemstatus',
            options={'verbose_name_plural': 'InOutStatus'},
        ),
        migrations.AlterModelOptions(
            name='techinventory',
            options={'verbose_name_plural': 'Tech Inventory'},
        ),
    ]
