# Generated by Django 4.1.5 on 2023-02-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManager', '0004_rename_inoutstatus_itemstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemstatus',
            options={'verbose_name_plural': 'Item Statuses'},
        ),
        migrations.AlterField(
            model_name='barcodes',
            name='upc',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
