# Generated by Django 4.1.5 on 2023-02-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManager', '0005_alter_itemstatus_options_alter_barcodes_upc'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'House Rooms',
            },
        ),
        migrations.AlterModelOptions(
            name='usedescription',
            options={'verbose_name_plural': 'Use Descriptions'},
        ),
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loaned_out', models.BooleanField(default=False)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.barcodes')),
            ],
            options={
                'verbose_name_plural': 'Loan Statuses',
            },
        ),
        migrations.CreateModel(
            name='ItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_details', models.CharField(max_length=1000)),
                ('LoanStatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.loanstatus')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.barcodes')),
                ('location_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='InventoryManager.houserooms')),
            ],
        ),
    ]
