# Generated by Django 4.1.5 on 2023-02-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManager', '0006_houserooms_alter_usedescription_options_loanstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlocation',
            name='LoanStatus',
        ),
        migrations.AddField(
            model_name='itemlocation',
            name='is_loaned_out',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LoanStatus',
        ),
    ]
